services:
  mb-ia-url-archiver:
    container_name: mb-ia-url-archiver
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    environment:
      - RUN_MODE=production
      - APP_PUSH_GATEWAY=pushgateway:9091
    networks:
      - musicbrainz-docker_default
      - default

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - default
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ../prometheus.yaml:/etc/prometheus/prometheus.yaml
    depends_on:
      - pushgateway

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    networks:
      - default
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../grafana/datasources:/etc/grafana/provisioning/datasources
      - ../grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - default

networks:
  default:
  musicbrainz-docker_default:
    external: true
